name: CI & Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        if: success()
        run: |
          npx gh-pages -d dist
